// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlseaSolarApi.Api.Infrastructure.Persistence;

#nullable disable

namespace SlseaSolarApi.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SolarDbContext))]
    [Migration("20261004170503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProvinceId", "Name")
                        .IsUnique();

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.GenerationReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EnergyKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PowerKw")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolarInstallationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Voltage")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SolarInstallationId", "SequenceNo")
                        .IsUnique();

                    b.HasIndex("SolarInstallationId", "Timestamp")
                        .IsUnique();

                    b.ToTable("GenerationReadings", (string)null);
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.GridSubstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapacityKw")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DistrictId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DistrictId");

                    b.ToTable("GridSubstations", (string)null);
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.SolarInstallation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapacityKw")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CommissionedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GridSubstationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InverterId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GridSubstationId");

                    b.HasIndex("MeterId")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("SolarInstallations", (string)null);
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.District", b =>
                {
                    b.HasOne("SlseaSolarApi.Api.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.GenerationReading", b =>
                {
                    b.HasOne("SlseaSolarApi.Api.Domain.Entities.SolarInstallation", "SolarInstallation")
                        .WithMany("Readings")
                        .HasForeignKey("SolarInstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarInstallation");
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.GridSubstation", b =>
                {
                    b.HasOne("SlseaSolarApi.Api.Domain.Entities.District", "District")
                        .WithMany("GridSubstations")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.SolarInstallation", b =>
                {
                    b.HasOne("SlseaSolarApi.Api.Domain.Entities.GridSubstation", "GridSubstation")
                        .WithMany("Installations")
                        .HasForeignKey("GridSubstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GridSubstation");
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("SlseaSolarApi.Api.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SlseaSolarApi.Api.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.District", b =>
                {
                    b.Navigation("GridSubstations");
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.GridSubstation", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("SlseaSolarApi.Api.Domain.Entities.SolarInstallation", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
